dist: trusty
sudo: required

branches:
  except:
    - master

language: bash

services:
  - docker

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sed -i 's/git@github.com:/https:\/\/github.com\//' www/.gitmodules
  - cd www
  - git submodule update --init
  - cd ..
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - source ./config.sh

script: ./build.sh

after_success:
  - tag=$(docker run --rm $REPO /bin/sh -c 'echo $TUPYONLINE_VERSION')
  - docker tag $REPO $REPO:$tag
  - docker push $REPO:latest
  - docker push $REPO:$tag
